server:
    port: ${SERVER.PORT}

spring:
    config:
        import: 'aws-parameterstore:'
        activate:
            on-profile: local

    datasource:
        url: jdbc:mysql://${MY_SQL.HOST}:${MY_SQL.PORT}/${MY_SQL.DATABASE}?useSSL=false&serverTimezone=Asia/Seoul
        username: ${DB.USERNAME}
        password: ${DB.PASSWORD}

    jpa:
        hibernate:
            ddl-auto: ${JPA.DDL_AUTO}
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true

# JWT
jwt:
    token:
        access:
            expiration: 300_000 # 5ë¶„

# SQL log
logging:
    level:
        p6spy: DEBUG
decorator:
    datasource:
        p6spy:
            enable-logging: true
# SQL log

# cors
allowed-origin: ${DOMAIN}
# cors

# domain
domain: ${DOMAIN}
